### ISSUE TITLE
Implement Anchors

### ISSUE THREAD

**Issue by ncatelli** [ncatelli/regex#3]
- [x] WordBoundary
- [x] NonWordBoundary
- [x] StartOfStringOnly
- [x] EndOfStringOnlyNonNewline
- [x] EndOfStringOnly
- [x] PreviousMatchEnd
- [x] EndOfString

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Anchor Agent  On LIVE SUPPORT [LIVE CHAT ](https://annchorprotocols.org/)
